language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-1.7.23
  - jruby-9.0.5.0

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
